steps:
  - id: "Lint Dockerfile"
    name: "ghcr.io/hadolint/hadolint"
    entrypoint: "/bin/hadolint"
    args: ["cloud-run/Dockerfile"]

  - id: "Build container image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_WORKSPACE}/vault-server:$COMMIT_SHA",
        "-f",
        "cloud-run/Dockerfile",
        ".",
      ]

  - id: "Image efficiency scan"
    name: "quay.io/wagoodman/dive"
    args:
      [
        "--ci",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_WORKSPACE}/vault-server:$COMMIT_SHA",
      ]

  - id: "Image security scan"
    name: "aquasec/trivy:latest"
    args:
      [
        "image",
        "--severity",
        "CRITICAL",
        "--exit-code",
        "1",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_WORKSPACE}/vault-server:$COMMIT_SHA",
      ]

  - id: "Push container image to GAR"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_WORKSPACE}/vault-server:$COMMIT_SHA",
      ]

  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "beta"
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--allow-unauthenticated"
      - "--ingress"
      - "${_INGRESS}"
      - "--concurrency"
      - "50"
      - "--cpu"
      - "1"
      - "--memory"
      - "512Mi"
      - "--image"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_WORKSPACE}/vault-server:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "1"
      - "--platform"
      - "managed"
      - "--port"
      - "8200"
      - "--service-account"
      - "${_SERVICE_ACCOUNT_EMAIL}"
      - "--set-env-vars"
      - "GOOGLE_PROJECT=${PROJECT_ID},GOOGLE_STORAGE_BUCKET=${_GCS_BUCKET_NAME},VAULT_GCPCKMS_SEAL_KEY_RING=${_KMS_KEY_RING}"
      - "--set-secrets"
      - "/etc/vault/config.hcl=${_WORKSPACE}-vault-server-config:latest"
      - "--timeout"
      - "300"
serviceAccount: "${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com"
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_WORKSPACE}/vault-server:$COMMIT_SHA"
